/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: chord.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "chord.pb-c.h"
void   node__init
                     (Node         *message)
{
  static const Node init_value = NODE__INIT;
  *message = init_value;
}
size_t node__get_packed_size
                     (const Node *message)
{
  assert(message->base.descriptor == &node__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t node__pack
                     (const Node *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &node__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t node__pack_to_buffer
                     (const Node *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &node__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Node *
       node__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Node *)
     protobuf_c_message_unpack (&node__descriptor,
                                allocator, len, data);
}
void   node__free_unpacked
                     (Node *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &node__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   notify_request__init
                     (NotifyRequest         *message)
{
  static const NotifyRequest init_value = NOTIFY_REQUEST__INIT;
  *message = init_value;
}
size_t notify_request__get_packed_size
                     (const NotifyRequest *message)
{
  assert(message->base.descriptor == &notify_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t notify_request__pack
                     (const NotifyRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &notify_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t notify_request__pack_to_buffer
                     (const NotifyRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &notify_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NotifyRequest *
       notify_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NotifyRequest *)
     protobuf_c_message_unpack (&notify_request__descriptor,
                                allocator, len, data);
}
void   notify_request__free_unpacked
                     (NotifyRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &notify_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   notify_response__init
                     (NotifyResponse         *message)
{
  static const NotifyResponse init_value = NOTIFY_RESPONSE__INIT;
  *message = init_value;
}
size_t notify_response__get_packed_size
                     (const NotifyResponse *message)
{
  assert(message->base.descriptor == &notify_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t notify_response__pack
                     (const NotifyResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &notify_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t notify_response__pack_to_buffer
                     (const NotifyResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &notify_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NotifyResponse *
       notify_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NotifyResponse *)
     protobuf_c_message_unpack (&notify_response__descriptor,
                                allocator, len, data);
}
void   notify_response__free_unpacked
                     (NotifyResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &notify_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   find_succ_request__init
                     (FindSuccRequest         *message)
{
  static const FindSuccRequest init_value = FIND_SUCC_REQUEST__INIT;
  *message = init_value;
}
size_t find_succ_request__get_packed_size
                     (const FindSuccRequest *message)
{
  assert(message->base.descriptor == &find_succ_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t find_succ_request__pack
                     (const FindSuccRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &find_succ_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t find_succ_request__pack_to_buffer
                     (const FindSuccRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &find_succ_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FindSuccRequest *
       find_succ_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FindSuccRequest *)
     protobuf_c_message_unpack (&find_succ_request__descriptor,
                                allocator, len, data);
}
void   find_succ_request__free_unpacked
                     (FindSuccRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &find_succ_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   find_succ_response__init
                     (FindSuccResponse         *message)
{
  static const FindSuccResponse init_value = FIND_SUCC_RESPONSE__INIT;
  *message = init_value;
}
size_t find_succ_response__get_packed_size
                     (const FindSuccResponse *message)
{
  assert(message->base.descriptor == &find_succ_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t find_succ_response__pack
                     (const FindSuccResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &find_succ_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t find_succ_response__pack_to_buffer
                     (const FindSuccResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &find_succ_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FindSuccResponse *
       find_succ_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FindSuccResponse *)
     protobuf_c_message_unpack (&find_succ_response__descriptor,
                                allocator, len, data);
}
void   find_succ_response__free_unpacked
                     (FindSuccResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &find_succ_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   r_find_succ_request__init
                     (RFindSuccRequest         *message)
{
  static const RFindSuccRequest init_value = R_FIND_SUCC_REQUEST__INIT;
  *message = init_value;
}
size_t r_find_succ_request__get_packed_size
                     (const RFindSuccRequest *message)
{
  assert(message->base.descriptor == &r_find_succ_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t r_find_succ_request__pack
                     (const RFindSuccRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &r_find_succ_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t r_find_succ_request__pack_to_buffer
                     (const RFindSuccRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &r_find_succ_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RFindSuccRequest *
       r_find_succ_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RFindSuccRequest *)
     protobuf_c_message_unpack (&r_find_succ_request__descriptor,
                                allocator, len, data);
}
void   r_find_succ_request__free_unpacked
                     (RFindSuccRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &r_find_succ_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   r_find_succ_response__init
                     (RFindSuccResponse         *message)
{
  static const RFindSuccResponse init_value = R_FIND_SUCC_RESPONSE__INIT;
  *message = init_value;
}
size_t r_find_succ_response__get_packed_size
                     (const RFindSuccResponse *message)
{
  assert(message->base.descriptor == &r_find_succ_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t r_find_succ_response__pack
                     (const RFindSuccResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &r_find_succ_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t r_find_succ_response__pack_to_buffer
                     (const RFindSuccResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &r_find_succ_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RFindSuccResponse *
       r_find_succ_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RFindSuccResponse *)
     protobuf_c_message_unpack (&r_find_succ_response__descriptor,
                                allocator, len, data);
}
void   r_find_succ_response__free_unpacked
                     (RFindSuccResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &r_find_succ_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   get_pred_request__init
                     (GetPredRequest         *message)
{
  static const GetPredRequest init_value = GET_PRED_REQUEST__INIT;
  *message = init_value;
}
size_t get_pred_request__get_packed_size
                     (const GetPredRequest *message)
{
  assert(message->base.descriptor == &get_pred_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t get_pred_request__pack
                     (const GetPredRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &get_pred_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t get_pred_request__pack_to_buffer
                     (const GetPredRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &get_pred_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetPredRequest *
       get_pred_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetPredRequest *)
     protobuf_c_message_unpack (&get_pred_request__descriptor,
                                allocator, len, data);
}
void   get_pred_request__free_unpacked
                     (GetPredRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &get_pred_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   get_pred_response__init
                     (GetPredResponse         *message)
{
  static const GetPredResponse init_value = GET_PRED_RESPONSE__INIT;
  *message = init_value;
}
size_t get_pred_response__get_packed_size
                     (const GetPredResponse *message)
{
  assert(message->base.descriptor == &get_pred_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t get_pred_response__pack
                     (const GetPredResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &get_pred_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t get_pred_response__pack_to_buffer
                     (const GetPredResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &get_pred_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetPredResponse *
       get_pred_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetPredResponse *)
     protobuf_c_message_unpack (&get_pred_response__descriptor,
                                allocator, len, data);
}
void   get_pred_response__free_unpacked
                     (GetPredResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &get_pred_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   check_pred_request__init
                     (CheckPredRequest         *message)
{
  static const CheckPredRequest init_value = CHECK_PRED_REQUEST__INIT;
  *message = init_value;
}
size_t check_pred_request__get_packed_size
                     (const CheckPredRequest *message)
{
  assert(message->base.descriptor == &check_pred_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t check_pred_request__pack
                     (const CheckPredRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &check_pred_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t check_pred_request__pack_to_buffer
                     (const CheckPredRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &check_pred_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CheckPredRequest *
       check_pred_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CheckPredRequest *)
     protobuf_c_message_unpack (&check_pred_request__descriptor,
                                allocator, len, data);
}
void   check_pred_request__free_unpacked
                     (CheckPredRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &check_pred_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   check_pred_response__init
                     (CheckPredResponse         *message)
{
  static const CheckPredResponse init_value = CHECK_PRED_RESPONSE__INIT;
  *message = init_value;
}
size_t check_pred_response__get_packed_size
                     (const CheckPredResponse *message)
{
  assert(message->base.descriptor == &check_pred_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t check_pred_response__pack
                     (const CheckPredResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &check_pred_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t check_pred_response__pack_to_buffer
                     (const CheckPredResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &check_pred_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CheckPredResponse *
       check_pred_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CheckPredResponse *)
     protobuf_c_message_unpack (&check_pred_response__descriptor,
                                allocator, len, data);
}
void   check_pred_response__free_unpacked
                     (CheckPredResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &check_pred_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   get_succ_list_request__init
                     (GetSuccListRequest         *message)
{
  static const GetSuccListRequest init_value = GET_SUCC_LIST_REQUEST__INIT;
  *message = init_value;
}
size_t get_succ_list_request__get_packed_size
                     (const GetSuccListRequest *message)
{
  assert(message->base.descriptor == &get_succ_list_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t get_succ_list_request__pack
                     (const GetSuccListRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &get_succ_list_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t get_succ_list_request__pack_to_buffer
                     (const GetSuccListRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &get_succ_list_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetSuccListRequest *
       get_succ_list_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetSuccListRequest *)
     protobuf_c_message_unpack (&get_succ_list_request__descriptor,
                                allocator, len, data);
}
void   get_succ_list_request__free_unpacked
                     (GetSuccListRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &get_succ_list_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   get_succ_list_response__init
                     (GetSuccListResponse         *message)
{
  static const GetSuccListResponse init_value = GET_SUCC_LIST_RESPONSE__INIT;
  *message = init_value;
}
size_t get_succ_list_response__get_packed_size
                     (const GetSuccListResponse *message)
{
  assert(message->base.descriptor == &get_succ_list_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t get_succ_list_response__pack
                     (const GetSuccListResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &get_succ_list_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t get_succ_list_response__pack_to_buffer
                     (const GetSuccListResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &get_succ_list_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetSuccListResponse *
       get_succ_list_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetSuccListResponse *)
     protobuf_c_message_unpack (&get_succ_list_response__descriptor,
                                allocator, len, data);
}
void   get_succ_list_response__free_unpacked
                     (GetSuccListResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &get_succ_list_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chord_message__init
                     (ChordMessage         *message)
{
  static const ChordMessage init_value = CHORD_MESSAGE__INIT;
  *message = init_value;
}
size_t chord_message__get_packed_size
                     (const ChordMessage *message)
{
  assert(message->base.descriptor == &chord_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chord_message__pack
                     (const ChordMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chord_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chord_message__pack_to_buffer
                     (const ChordMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chord_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChordMessage *
       chord_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChordMessage *)
     protobuf_c_message_unpack (&chord_message__descriptor,
                                allocator, len, data);
}
void   chord_message__free_unpacked
                     (ChordMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chord_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor node__field_descriptors[3] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED64,
    0,   /* quantifier_offset */
    offsetof(Node, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Node, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Node, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned node__field_indices_by_name[] = {
  1,   /* field[1] = address */
  0,   /* field[0] = key */
  2,   /* field[2] = port */
};
static const ProtobufCIntRange node__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor node__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Node",
  "Node",
  "Node",
  "",
  sizeof(Node),
  3,
  node__field_descriptors,
  node__field_indices_by_name,
  1,  node__number_ranges,
  (ProtobufCMessageInit) node__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor notify_request__field_descriptors[1] =
{
  {
    "node",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(NotifyRequest, node),
    &node__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned notify_request__field_indices_by_name[] = {
  0,   /* field[0] = node */
};
static const ProtobufCIntRange notify_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor notify_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NotifyRequest",
  "NotifyRequest",
  "NotifyRequest",
  "",
  sizeof(NotifyRequest),
  1,
  notify_request__field_descriptors,
  notify_request__field_indices_by_name,
  1,  notify_request__number_ranges,
  (ProtobufCMessageInit) notify_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define notify_response__field_descriptors NULL
#define notify_response__field_indices_by_name NULL
#define notify_response__number_ranges NULL
const ProtobufCMessageDescriptor notify_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NotifyResponse",
  "NotifyResponse",
  "NotifyResponse",
  "",
  sizeof(NotifyResponse),
  0,
  notify_response__field_descriptors,
  notify_response__field_indices_by_name,
  0,  notify_response__number_ranges,
  (ProtobufCMessageInit) notify_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor find_succ_request__field_descriptors[1] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED64,
    0,   /* quantifier_offset */
    offsetof(FindSuccRequest, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned find_succ_request__field_indices_by_name[] = {
  0,   /* field[0] = key */
};
static const ProtobufCIntRange find_succ_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor find_succ_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FindSuccRequest",
  "FindSuccRequest",
  "FindSuccRequest",
  "",
  sizeof(FindSuccRequest),
  1,
  find_succ_request__field_descriptors,
  find_succ_request__field_indices_by_name,
  1,  find_succ_request__number_ranges,
  (ProtobufCMessageInit) find_succ_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor find_succ_response__field_descriptors[1] =
{
  {
    "node",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(FindSuccResponse, node),
    &node__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned find_succ_response__field_indices_by_name[] = {
  0,   /* field[0] = node */
};
static const ProtobufCIntRange find_succ_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor find_succ_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FindSuccResponse",
  "FindSuccResponse",
  "FindSuccResponse",
  "",
  sizeof(FindSuccResponse),
  1,
  find_succ_response__field_descriptors,
  find_succ_response__field_indices_by_name,
  1,  find_succ_response__number_ranges,
  (ProtobufCMessageInit) find_succ_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor r_find_succ_request__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED64,
    0,   /* quantifier_offset */
    offsetof(RFindSuccRequest, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "requester",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RFindSuccRequest, requester),
    &node__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned r_find_succ_request__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = requester */
};
static const ProtobufCIntRange r_find_succ_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor r_find_succ_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rFindSuccRequest",
  "RFindSuccRequest",
  "RFindSuccRequest",
  "",
  sizeof(RFindSuccRequest),
  2,
  r_find_succ_request__field_descriptors,
  r_find_succ_request__field_indices_by_name,
  1,  r_find_succ_request__number_ranges,
  (ProtobufCMessageInit) r_find_succ_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor r_find_succ_response__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED64,
    0,   /* quantifier_offset */
    offsetof(RFindSuccResponse, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RFindSuccResponse, node),
    &node__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned r_find_succ_response__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = node */
};
static const ProtobufCIntRange r_find_succ_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor r_find_succ_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rFindSuccResponse",
  "RFindSuccResponse",
  "RFindSuccResponse",
  "",
  sizeof(RFindSuccResponse),
  2,
  r_find_succ_response__field_descriptors,
  r_find_succ_response__field_indices_by_name,
  1,  r_find_succ_response__number_ranges,
  (ProtobufCMessageInit) r_find_succ_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define get_pred_request__field_descriptors NULL
#define get_pred_request__field_indices_by_name NULL
#define get_pred_request__number_ranges NULL
const ProtobufCMessageDescriptor get_pred_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GetPredRequest",
  "GetPredRequest",
  "GetPredRequest",
  "",
  sizeof(GetPredRequest),
  0,
  get_pred_request__field_descriptors,
  get_pred_request__field_indices_by_name,
  0,  get_pred_request__number_ranges,
  (ProtobufCMessageInit) get_pred_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor get_pred_response__field_descriptors[1] =
{
  {
    "node",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GetPredResponse, node),
    &node__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned get_pred_response__field_indices_by_name[] = {
  0,   /* field[0] = node */
};
static const ProtobufCIntRange get_pred_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor get_pred_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GetPredResponse",
  "GetPredResponse",
  "GetPredResponse",
  "",
  sizeof(GetPredResponse),
  1,
  get_pred_response__field_descriptors,
  get_pred_response__field_indices_by_name,
  1,  get_pred_response__number_ranges,
  (ProtobufCMessageInit) get_pred_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define check_pred_request__field_descriptors NULL
#define check_pred_request__field_indices_by_name NULL
#define check_pred_request__number_ranges NULL
const ProtobufCMessageDescriptor check_pred_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CheckPredRequest",
  "CheckPredRequest",
  "CheckPredRequest",
  "",
  sizeof(CheckPredRequest),
  0,
  check_pred_request__field_descriptors,
  check_pred_request__field_indices_by_name,
  0,  check_pred_request__number_ranges,
  (ProtobufCMessageInit) check_pred_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define check_pred_response__field_descriptors NULL
#define check_pred_response__field_indices_by_name NULL
#define check_pred_response__number_ranges NULL
const ProtobufCMessageDescriptor check_pred_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CheckPredResponse",
  "CheckPredResponse",
  "CheckPredResponse",
  "",
  sizeof(CheckPredResponse),
  0,
  check_pred_response__field_descriptors,
  check_pred_response__field_indices_by_name,
  0,  check_pred_response__number_ranges,
  (ProtobufCMessageInit) check_pred_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define get_succ_list_request__field_descriptors NULL
#define get_succ_list_request__field_indices_by_name NULL
#define get_succ_list_request__number_ranges NULL
const ProtobufCMessageDescriptor get_succ_list_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GetSuccListRequest",
  "GetSuccListRequest",
  "GetSuccListRequest",
  "",
  sizeof(GetSuccListRequest),
  0,
  get_succ_list_request__field_descriptors,
  get_succ_list_request__field_indices_by_name,
  0,  get_succ_list_request__number_ranges,
  (ProtobufCMessageInit) get_succ_list_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor get_succ_list_response__field_descriptors[1] =
{
  {
    "successors",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GetSuccListResponse, n_successors),
    offsetof(GetSuccListResponse, successors),
    &node__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned get_succ_list_response__field_indices_by_name[] = {
  0,   /* field[0] = successors */
};
static const ProtobufCIntRange get_succ_list_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor get_succ_list_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GetSuccListResponse",
  "GetSuccListResponse",
  "GetSuccListResponse",
  "",
  sizeof(GetSuccListResponse),
  1,
  get_succ_list_response__field_descriptors,
  get_succ_list_response__field_indices_by_name,
  1,  get_succ_list_response__number_ranges,
  (ProtobufCMessageInit) get_succ_list_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const uint32_t chord_message__version__default_value = 417u;
static const ProtobufCFieldDescriptor chord_message__field_descriptors[14] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ChordMessage, version),
    NULL,
    &chord_message__version__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "notify_req",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, notify_req),
    &notify_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "notify_resp",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, notify_resp),
    &notify_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "find_succ_req",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, find_succ_req),
    &find_succ_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "find_succ_resp",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, find_succ_resp),
    &find_succ_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get_pred_req",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, get_pred_req),
    &get_pred_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get_pred_resp",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, get_pred_resp),
    &get_pred_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "check_pred_req",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, check_pred_req),
    &check_pred_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "check_pred_resp",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, check_pred_resp),
    &check_pred_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get_succ_list_req",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, get_succ_list_req),
    &get_succ_list_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get_succ_list_resp",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, get_succ_list_resp),
    &get_succ_list_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_find_succ_req",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, r_find_succ_req),
    &r_find_succ_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_find_succ_resp",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, r_find_succ_resp),
    &r_find_succ_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "query_id",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ChordMessage, has_query_id),
    offsetof(ChordMessage, query_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chord_message__field_indices_by_name[] = {
  7,   /* field[7] = check_pred_req */
  8,   /* field[8] = check_pred_resp */
  3,   /* field[3] = find_succ_req */
  4,   /* field[4] = find_succ_resp */
  5,   /* field[5] = get_pred_req */
  6,   /* field[6] = get_pred_resp */
  9,   /* field[9] = get_succ_list_req */
  10,   /* field[10] = get_succ_list_resp */
  1,   /* field[1] = notify_req */
  2,   /* field[2] = notify_resp */
  13,   /* field[13] = query_id */
  11,   /* field[11] = r_find_succ_req */
  12,   /* field[12] = r_find_succ_resp */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange chord_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor chord_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ChordMessage",
  "ChordMessage",
  "ChordMessage",
  "",
  sizeof(ChordMessage),
  14,
  chord_message__field_descriptors,
  chord_message__field_indices_by_name,
  1,  chord_message__number_ranges,
  (ProtobufCMessageInit) chord_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
